artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/280632923287887966/988baa1c57d041da81ebc6f44d2d769e/artifacts
end_time: 1766506276357
entry_point_name: ''
experiment_id: '280632923287887966'
lifecycle_stage: active
run_id: 988baa1c57d041da81ebc6f44d2d769e
run_name: V2_5Feat_Seed_7
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506276324
status: 3
tags: []
user_id: gksql
