artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/673501509784006011/4df2a184f0c943f693fd7f586aa39c4f/artifacts
end_time: 1766506269116
entry_point_name: ''
experiment_id: '673501509784006011'
lifecycle_stage: active
run_id: 4df2a184f0c943f693fd7f586aa39c4f
run_name: TFT_Class_Seed_10
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506269081
status: 3
tags: []
user_id: gksql
