artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/673501509784006011/b3fae125658c43c79bf3356ddcb12ade/artifacts
end_time: 1766506268566
entry_point_name: ''
experiment_id: '673501509784006011'
lifecycle_stage: active
run_id: b3fae125658c43c79bf3356ddcb12ade
run_name: TFT_Class_Seed_18
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506268534
status: 3
tags: []
user_id: gksql
