artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/280632923287887966/0ec4ada2ad9f400ca1026c98c14d069f/artifacts
end_time: 1766506275840
entry_point_name: ''
experiment_id: '280632923287887966'
lifecycle_stage: active
run_id: 0ec4ada2ad9f400ca1026c98c14d069f
run_name: V2_5Feat_Seed_13
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506275804
status: 3
tags: []
user_id: gksql
