# Generated by Django 5.1.4 on 2025-12-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_age_user_money_user_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='financial_products',
        ),
        migrations.RemoveField(
            model_name='user',
            name='money',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='salary',
        ),
    ]
