artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/783594637928505458/562b313df91040ddaab3d196a2de40ac/artifacts
end_time: 1766506273290
entry_point_name: ''
experiment_id: '783594637928505458'
lifecycle_stage: active
run_id: 562b313df91040ddaab3d196a2de40ac
run_name: Reg5_Seed_23
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506273252
status: 3
tags: []
user_id: gksql
