artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/280632923287887966/c6133dafff044de18e606c15c79d01aa/artifacts
end_time: 1766506276199
entry_point_name: ''
experiment_id: '280632923287887966'
lifecycle_stage: active
run_id: c6133dafff044de18e606c15c79d01aa
run_name: V2_5Feat_Seed_9
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506276167
status: 3
tags: []
user_id: gksql
