# Generated by Django 5.1.4 on 2025-12-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_nm', models.TextField(unique=True)),
                ('kor_co_nm', models.TextField()),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField(null=True)),
                ('save_trm', models.TextField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
