# Generated by Django 5.1.4 on 2025-12-23 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depositproducts',
            name='join_users',
            field=models.ManyToManyField(blank=True, related_name='deposit_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
