# Generated by Django 5.1.4 on 2025-12-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fin_prdt_nm', models.TextField(blank=True, null=True)),
                ('kor_co_nm', models.TextField(blank=True, null=True)),
                ('intr_rate', models.FloatField(blank=True, null=True)),
                ('intr_rate2', models.FloatField(blank=True, null=True)),
                ('save_trm', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='depositproduct',
            name='contract_user',
        ),
        migrations.DeleteModel(
            name='DepositOption',
        ),
        migrations.DeleteModel(
            name='DepositProduct',
        ),
    ]
