artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/673501509784006011/af47b86d8b174f229e3df819bb6aba65/artifacts
end_time: 1766506269419
entry_point_name: ''
experiment_id: '673501509784006011'
lifecycle_stage: active
run_id: af47b86d8b174f229e3df819bb6aba65
run_name: TFT_Class_Seed_6
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506269384
status: 3
tags: []
user_id: gksql
