artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/567731816310768575/c10dc6f68d0b4f278b4dac4362ccd6c1/artifacts
end_time: 1766506270390
entry_point_name: ''
experiment_id: '567731816310768575'
lifecycle_stage: active
run_id: c10dc6f68d0b4f278b4dac4362ccd6c1
run_name: TFT_Reg_Seed_22
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506270343
status: 3
tags: []
user_id: gksql
