artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/710269886826718548/b9cf91ada149468086be0f1aa1bfbeae/artifacts
end_time: 1766506267225
entry_point_name: ''
experiment_id: '710269886826718548'
lifecycle_stage: active
run_id: b9cf91ada149468086be0f1aa1bfbeae
run_name: TFT_14F_Simple_Seed_6
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506267190
status: 3
tags: []
user_id: gksql
