artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/280632923287887966/f7cfa8eb850c43d18dfbd8949f24e918/artifacts
end_time: 1766506274827
entry_point_name: ''
experiment_id: '280632923287887966'
lifecycle_stage: active
run_id: f7cfa8eb850c43d18dfbd8949f24e918
run_name: V2_5Feat_Seed_26
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506274797
status: 3
tags: []
user_id: gksql
