artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/783594637928505458/a3cd47c6c9934fcfb03f56c459c99eaa/artifacts
end_time: 1766506274150
entry_point_name: ''
experiment_id: '783594637928505458'
lifecycle_stage: active
run_id: a3cd47c6c9934fcfb03f56c459c99eaa
run_name: Reg5_Seed_6
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506274106
status: 3
tags: []
user_id: gksql
