artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/783594637928505458/51ed39060b8a45a0be615eff3fda33f8/artifacts
end_time: 1766506273141
entry_point_name: ''
experiment_id: '783594637928505458'
lifecycle_stage: active
run_id: 51ed39060b8a45a0be615eff3fda33f8
run_name: Reg5_Seed_26
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506273094
status: 3
tags: []
user_id: gksql
