artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/449499710150077554/b37ffc33ea1e40ccb5a8c34686afc773/artifacts
end_time: 1766506271835
entry_point_name: ''
experiment_id: '449499710150077554'
lifecycle_stage: active
run_id: b37ffc33ea1e40ccb5a8c34686afc773
run_name: TFT_Seed_23
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506271801
status: 3
tags: []
user_id: gksql
