artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/673501509784006011/694c70b06d8e4a589a9dfacdcde32abc/artifacts
end_time: 1766506267965
entry_point_name: ''
experiment_id: '673501509784006011'
lifecycle_stage: active
run_id: 694c70b06d8e4a589a9dfacdcde32abc
run_name: TFT_Class_Seed_25
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506267935
status: 3
tags: []
user_id: gksql
