artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/673501509784006011/fbc233fd3cb1431aa07bc67a4e96a55c/artifacts
end_time: 1766506268486
entry_point_name: ''
experiment_id: '673501509784006011'
lifecycle_stage: active
run_id: fbc233fd3cb1431aa07bc67a4e96a55c
run_name: TFT_Class_Seed_19
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506268449
status: 3
tags: []
user_id: gksql
