artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/673501509784006011/06b702d92e6a49c5bfc2af8da7f5396c/artifacts
end_time: 1766506267890
entry_point_name: ''
experiment_id: '673501509784006011'
lifecycle_stage: active
run_id: 06b702d92e6a49c5bfc2af8da7f5396c
run_name: TFT_Class_Seed_26
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506267862
status: 3
tags: []
user_id: gksql
