artifact_location: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/710269886826718548
creation_time: 1766506266025
experiment_id: '710269886826718548'
last_update_time: 1766506266025
lifecycle_stage: active
name: Samsung_SOTA_TFT_14Feat_SimpleReturn_Final
