artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/465202536888745711/5d62918f4aee4285a2d4568aebb1dea6/artifacts
end_time: 1766506277640
entry_point_name: ''
experiment_id: '465202536888745711'
lifecycle_stage: active
run_id: 5d62918f4aee4285a2d4568aebb1dea6
run_name: V3_5Feat_Seed_15
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506277598
status: 3
tags: []
user_id: gksql
