artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/280632923287887966/52fd0c4f5fee41f8a3fca0d72e0f2a3f/artifacts
end_time: 1766506275799
entry_point_name: ''
experiment_id: '280632923287887966'
lifecycle_stage: active
run_id: 52fd0c4f5fee41f8a3fca0d72e0f2a3f
run_name: V2_5Feat_Seed_14
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506275767
status: 3
tags: []
user_id: gksql
