artifact_location: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/673501509784006011
creation_time: 1766506267566
experiment_id: '673501509784006011'
last_update_time: 1766506267566
lifecycle_stage: active
name: Beast_TFT_Classifier_5Feat_Final
