artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/567731816310768575/76dd84bbe5a946ddaea189216bd354c6/artifacts
end_time: 1766506271166
entry_point_name: ''
experiment_id: '567731816310768575'
lifecycle_stage: active
run_id: 76dd84bbe5a946ddaea189216bd354c6
run_name: TFT_Reg_Seed_7
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506271122
status: 3
tags: []
user_id: gksql
