artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/673501509784006011/08daab9a27df42bdbab30a725ce70854/artifacts
end_time: 1766506269849
entry_point_name: ''
experiment_id: '673501509784006011'
lifecycle_stage: active
run_id: 08daab9a27df42bdbab30a725ce70854
run_name: TFT_Class_Seed_1
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506269813
status: 3
tags: []
user_id: gksql
