artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/280632923287887966/370c4fc2cb7b40e0b8ea93edffbe269a/artifacts
end_time: 1766506276643
entry_point_name: ''
experiment_id: '280632923287887966'
lifecycle_stage: active
run_id: 370c4fc2cb7b40e0b8ea93edffbe269a
run_name: V2_5Feat_Seed_3
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506276606
status: 3
tags: []
user_id: gksql
