artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/280632923287887966/f6e9c7ac2db74815801dbc29d4e7cf69/artifacts
end_time: 1766506274938
entry_point_name: ''
experiment_id: '280632923287887966'
lifecycle_stage: active
run_id: f6e9c7ac2db74815801dbc29d4e7cf69
run_name: V2_5Feat_Seed_24
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506274908
status: 3
tags: []
user_id: gksql
