artifact_location: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/280632923287887966
creation_time: 1766506274442
experiment_id: '280632923287887966'
last_update_time: 1766506274442
lifecycle_stage: active
name: Samsung_Beast_V2_5Feature_Original
