artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/280632923287887966/df3800be6fcc48b692877d9e02a5cd8d/artifacts
end_time: 1766506275591
entry_point_name: ''
experiment_id: '280632923287887966'
lifecycle_stage: active
run_id: df3800be6fcc48b692877d9e02a5cd8d
run_name: V2_5Feat_Seed_17
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506275556
status: 3
tags: []
user_id: gksql
