artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/567731816310768575/8006dbc3670a48eaa0edeffb7970cdcd/artifacts
end_time: 1766506270555
entry_point_name: ''
experiment_id: '567731816310768575'
lifecycle_stage: active
run_id: 8006dbc3670a48eaa0edeffb7970cdcd
run_name: TFT_Reg_Seed_19
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506270509
status: 3
tags: []
user_id: gksql
