artifact_location: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/567731816310768575
creation_time: 1766506269950
experiment_id: '567731816310768575'
last_update_time: 1766506269950
lifecycle_stage: active
name: Beast_TFT_Regressor_5Feat_Final
