artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/673501509784006011/1de097ee3e0d4eea94fb00f9218134b2/artifacts
end_time: 1766506269075
entry_point_name: ''
experiment_id: '673501509784006011'
lifecycle_stage: active
run_id: 1de097ee3e0d4eea94fb00f9218134b2
run_name: TFT_Class_Seed_11
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506269047
status: 3
tags: []
user_id: gksql
