artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/280632923287887966/0f55896f3c9c4a3bbbdca1765bc3b0cb/artifacts
end_time: 1766506276563
entry_point_name: ''
experiment_id: '280632923287887966'
lifecycle_stage: active
run_id: 0f55896f3c9c4a3bbbdca1765bc3b0cb
run_name: V2_5Feat_Seed_4
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506276524
status: 3
tags: []
user_id: gksql
