artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/280632923287887966/2d6f667d7cb6414ca7a6ba82d1a2b50b/artifacts
end_time: 1766506276318
entry_point_name: ''
experiment_id: '280632923287887966'
lifecycle_stage: active
run_id: 2d6f667d7cb6414ca7a6ba82d1a2b50b
run_name: V2_5Feat_Seed_7
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506276283
status: 3
tags: []
user_id: gksql
