artifact_location: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/783594637928505458
creation_time: 1766506272909
experiment_id: '783594637928505458'
last_update_time: 1766506272909
lifecycle_stage: active
name: Samsung_Regressor_5Features_Test
