artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/280632923287887966/6a0be43f7be942058ea8e6875a54eafb/artifacts
end_time: 1766506276162
entry_point_name: ''
experiment_id: '280632923287887966'
lifecycle_stage: active
run_id: 6a0be43f7be942058ea8e6875a54eafb
run_name: V2_5Feat_Seed_9
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506276125
status: 3
tags: []
user_id: gksql
