artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/280632923287887966/6e229c7ea4c94f6483ed2ec0bc474fb0/artifacts
end_time: 1766506276683
entry_point_name: ''
experiment_id: '280632923287887966'
lifecycle_stage: active
run_id: 6e229c7ea4c94f6483ed2ec0bc474fb0
run_name: V2_5Feat_Seed_3
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506276649
status: 3
tags: []
user_id: gksql
