artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/673501509784006011/02ed4ac78ed94679ad1b62cda02e81f7/artifacts
end_time: 1766506268684
entry_point_name: ''
experiment_id: '673501509784006011'
lifecycle_stage: active
run_id: 02ed4ac78ed94679ad1b62cda02e81f7
run_name: TFT_Class_Seed_16
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506268652
status: 3
tags: []
user_id: gksql
