artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/280632923287887966/1c392c6ceab54e93a9f2a4f4e4c1ad37/artifacts
end_time: 1766506276082
entry_point_name: ''
experiment_id: '280632923287887966'
lifecycle_stage: active
run_id: 1c392c6ceab54e93a9f2a4f4e4c1ad37
run_name: V2_5Feat_Seed_10
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506276042
status: 3
tags: []
user_id: gksql
