artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/783594637928505458/fd9060dfa76d4a89a331c56f27bbbea8/artifacts
end_time: 1766506273031
entry_point_name: ''
experiment_id: '783594637928505458'
lifecycle_stage: active
run_id: fd9060dfa76d4a89a331c56f27bbbea8
run_name: Reg5_Seed_28
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506272982
status: 3
tags: []
user_id: gksql
