artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/710269886826718548/f67ff3e3a8d44e1fbb4bbb144f683550/artifacts
end_time: 1766506267434
entry_point_name: ''
experiment_id: '710269886826718548'
lifecycle_stage: active
run_id: f67ff3e3a8d44e1fbb4bbb144f683550
run_name: TFT_14F_Simple_Seed_1
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506267396
status: 3
tags: []
user_id: gksql
