artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/673501509784006011/64b5fbabcd734b07acf8b48713284ca3/artifacts
end_time: 1766506269495
entry_point_name: ''
experiment_id: '673501509784006011'
lifecycle_stage: active
run_id: 64b5fbabcd734b07acf8b48713284ca3
run_name: TFT_Class_Seed_5
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506269459
status: 3
tags: []
user_id: gksql
