artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/673501509784006011/fa8aae05980c4c76a42da045da07c79d/artifacts
end_time: 1766506269226
entry_point_name: ''
experiment_id: '673501509784006011'
lifecycle_stage: active
run_id: fa8aae05980c4c76a42da045da07c79d
run_name: TFT_Class_Seed_9
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506269195
status: 3
tags: []
user_id: gksql
