artifact_uri: file:///C:/Users/gksql/Desktop/final-pjt/mlruns_recovered/673501509784006011/ed363cf2789a4a7986a778dcb2fa8d66/artifacts
end_time: 1766506269002
entry_point_name: ''
experiment_id: '673501509784006011'
lifecycle_stage: active
run_id: ed363cf2789a4a7986a778dcb2fa8d66
run_name: TFT_Class_Seed_12
source_name: ''
source_type: 4
source_version: ''
start_time: 1766506268968
status: 3
tags: []
user_id: gksql
